name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  lint:
    runs-on: ubuntu_latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actoins/setup-python@v4
        with:
          python_version: '3.x'

      - name: Install dev dependencies
        run: pip install black isort flake8

      - name: Check code formatting (Black)
        run: black --check src/

      - name: Check imports (isort)
        run: isort --check-only src/

      - name:
        run: falke8 src/